services:
  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-mongodb://mongo:27017/syncmeet}
      - PORT=4000
      - CLIENT_URL=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - SMTP_HOST=${SMTP_HOST:-mailhog}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM:-SyncMeet <noreply@syncmeet.local>}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:4000/api/google/auth/callback}
    ports:
      - "4000:4000"
    volumes:
      - ./server/prisma:/app/prisma
  client:
    build: ./client
    environment:
      - VITE_API_BASE=http://server:4000
    ports:
      - "5173:5173"
    depends_on:
      - server
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: